name: overlandflow_usecase
channels:
  - conda-forge
dependencies:
  - python=3.9
  - landlab=2.5.0
  - pymt>=1.3.1
  - pymt_topography
  - pymt_era5
  - imageio-ffmpeg
  - cdsapi
  - numpy=1.23.5
  - xarray
  - imageio>=2.19.1
  - matplotlib
  - jupyter
  - tqdm
